/**
 * Service Catalog
 * Service catalog serves information about deployed models
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Swagger2 {
    /**
     * Base64 encoded OpenAPI 2.0 definition of MLServer API
     */
    raw?: string;

}
