# Version of Odahu UI
# By default .Chart.AppVersion version is used
# Type: string
# odahuVersion: "1.0"

# Docker images registry
# This registry will be used for automatic docker image name deduction based on OdahuFlow naming for images
# Each image could be overridden manually in .<service>.image, please see .api root section or other
# Type: string
imagesRegistry: odahu/

# Configuration of OdahuFlow ingresses
# Ingresses are for next <service>s
# - ui
ingress:
  # Global flag for Ingress enabling
  # Each Ingress could be configured manually in .<service>.ingress.enabled
  # Type: bool
  enabled: false

  # Root domain for auto-created Ingress domains.
  # Each domain could be configured manually in .<service>.ingress.domain
  # Also it controls building URLs for external resources such as auth endpoint
  # Type: string
  globalDomain: example.com

  # Global annotations for all services
  # Each Ingress could be configured manually in .<service>.ingress.annotations
  # Type: string->string map
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: "true"

  # Global TLS flag
  # Each Ingress could be configured manually in .<service>.ingress.tlsEnabled
  # Also it controls building URLs for external resources such as auth endpoint
  # Type: bool
  tlsEnabled: false

  # Global TLS secret name
  # Each Ingress could be configured manually in .<service>.ingress.tlsSecretName
  # Type: string
  tlsSecretName: ~

# Security configuration. Model API security configures in .modelApiSecurity section (see below)
security:
  # Is authorization for WEB requests enabled or not
  # Type: bool
  enabled: false

  # Type of authorization. Currently only oauth2_proxy is supported
  # Valid values are:
  # - oauth2_proxy
  integration: oauth2_proxy

  # Detail configuration of oauth2_proxy
  oauth2_proxy:
    # Internal URL of oauth2_proxy that will be called on each Ingress request. Is used in auth_request directive on Ingress Nginx
    # Type: string
    url: http://oauth2-proxy.kube-system.svc.cluster.local:4180/oauth2/auth

    # Public URL on which user will be redirected for authrorization
    # Uncomment for custom public URL, otherwise auth.<ingress.globalDomain> will be used
    # besides standard Nginx Ingress variables, escaped_request_uri is available too
    # Type: string
    # public_url: https://auth.my-company.com/oauth2/start?rd=https://$host$escaped_request_uri

    # OAuth's cookie name
    # Is required to add fix for big-sized cookies
    # SHOULD be same as in oauth2 proxy configuration
    # Type: string
    cookieName: _oauth2_proxy

# UI server configuration
ui:
  # This variable can be uncommented to setup custom image name for api (server)
  # Type: string
  # image: custom-image:1.0

  # Count of API replicas
  # Type: integer
  replicas: 1

  # Port on which API listens income traffic
  # Type: integer
  port: 80

  # Resources for each instance
  # For declaration format see https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  # Configuration of ingress object
  ingress:
    # Custom enabling/disabling of Ingress resource for API
    # To use specific value, uncomment and replace ~ with target value
    # Type: bool
    # enabled: ~

    # Annotations for ingress
    # Will be added to global annotations (.ingress.annotations)
    # Type: string->string map
    annotations: {}

    # Custom domain name
    # By default domain name "api.<..ingress.globalDomain>" is used
    # To use specific value, replace ~ with target value
    # Type: string
    # domain: ~
