/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface APIConfig {
    backend?: models.APIBackendConfig;

    /**
     * If true then only webserver will be setup. Without background workers responsible to monitor storage and call services
     */
    disableWorkers?: boolean;

    /**
     * API HTTP port
     */
    port?: number;

}
