/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AuthConfig {
    /**
     * It is a mock for the future. Currently, it is always empty.
     */
    apiToken?: string;

    /**
     * ODAHU API URL
     */
    apiUrl?: string;

    /**
     * OpenID client_id credential for service account
     */
    clientId?: string;

    /**
     * OpenID client_secret credential for service account
     */
    clientSecret?: string;

    /**
     * OpenID token url
     */
    oauthOidcTokenEndpoint?: string;

}
