/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BatchConfig {
    /**
     * Enable batch API/operator
     */
    enabled?: boolean;

    /**
     * Kubernetes namespace, where BatchInferenceService and BatchInferenceJob will be created
     */
    namespace?: string;

    /**
     * Node pools to run batch jobs
     */
    nodePools?: Array<models.NodePool>;

    /**
     * RClone image that will be used to sync data with object storage
     */
    rcloneImage?: string;

    /**
     * Specifies a ServiceAccount object that provides custom credentials for executing the TaskRun
     */
    serviceAccountName?: string;

    /**
     * Timeout for full batch process
     */
    timeout?: string;

    /**
     * Kubernetes tolerations for batch jobs
     */
    tolerations?: string;

    /**
     * ODAHU tools image
     */
    toolsImage?: string;

    /**
     * ODAHU tools image
     */
    toolsSecret?: string;

}
