/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CommonConfig {
    /**
     * Database connection string
     */
    databaseConnectionString?: string;

    /**
     * The collection of external urls, for example: metrics, edge, service catalog and so on
     */
    externalUrls?: Array<models.ExternalUrl>;

    /**
     * Graceful shutdown timeout
     */
    gracefulTimeout?: string;

    /**
     * How often launch new training
     */
    launchPeriod?: string;

    /**
     * OpenID token url
     */
    oauthOidcTokenEndpoint?: string;

    /**
     * Kubernetes can consume the GPU resource in the <vendor>.com/gpu format. For example, amd.com/gpu or nvidia.com/gpu.
     */
    resourceGpuName?: string;

    /**
     * Version of ODAHU platform
     */
    version?: string;

}
