/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Config {
    api?: models.APIConfig;

    common?: models.CommonConfig;

    connection?: models.ConnectionConfig;

    deployment?: models.ModelDeploymentConfig;

    operator?: models.OperatorConfig;

    packager?: models.PackagerConfig;

    packaging?: models.ModelPackagingConfig;

    serviceCatalog?: models.ServiceCatalog;

    trainer?: models.TrainerConfig;

    training?: models.ModelTrainingConfig;

    users?: models.UserConfig;

}
