/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ConnectionReference {
    /**
     * ODAHU Connection
     */
    connection?: string;

    /**
     * User can override path otherwise Connection path will be used. For dataSource: Input data files must have .json extension and be valid JSON files that follows [Predict Protocol - Version 2](https://github.com/kubeflow/kfserving/blob/v0.5.1/docs/predict-api/v2/required_api.md#inference-request-json-object). For outputDestination: Output data files must have .json extension and be valid JSON files that follows [Predict Protocol - Version 2](https://github.com/kubeflow/kfserving/blob/v0.5.1/docs/predict-api/v2/required_api.md#inference-response-json-object). nFor modelSource: If path has .zip / .tar.gz suffix then it will be unpacked before delivering to user predictor container. Otherwise its considered and a directory and will be delivered to user predictor container AS-IS
     */
    path?: string;

}
