/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DeploymentEvent {
    /**
     * When event is raised
     */
    datetime?: string;

    /**
     * EntityID contains ID of ModelDeployment for ModelDeploymentDeleted and ModelDeploymentDeletionMarkIsSet event types Does not make sense in case of ModelDeploymentUpdate, ModelDeploymentCreate, ModelDeploymentStatusUpdated events
     */
    entityID?: string;

    /**
     * Payload contains ModelDeployment for ModelDeploymentUpdate, ModelDeploymentCreate, ModelDeploymentStatusUpdated  events. Does not make sense in case of ModelDeploymentDelete, ModelDeploymentDeletionMarkIsSet events
     */
    payload?: models.ModelDeployment;

    /**
     * Possible values: ModelDeploymentCreate, ModelDeploymentUpdate, ModelRouteDeleted, ModelDeploymentDeletionMarkIsSet, ModelDeploymentStatusUpdated
     */
    type?: string;

}
