/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ExternalUrl {
    /**
     * Optional link to an image which represents a type of the resource, for example the logo of Grafana
     */
    imageUrl?: string;

    /**
     * Human-readable name
     */
    name?: string;

    /**
     * Link to a resource
     */
    url?: string;

}
