/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InferenceJobStatus {
    /**
     * Message is any message from runtime service about status of InferenceJob
     */
    message?: string;

    /**
     * PodName is a name of Pod in Kubernetes that is running under the hood of InferenceJob
     */
    podName?: string;

    /**
     * Reason is a reason of some InferenceJob state that was retrieved from runtime service. for example reason of failure
     */
    reason?: string;

    /**
     * State describes current state of InferenceJob
     */
    state?: string;

}
