/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelPackagingConfig {
    /**
     * Default resources for packaging pods
     */
    defaultResources?: models.ResourceRequirements;

    /**
     * Enable packaging API/operator
     */
    enabled?: boolean;

    modelPackagerImage?: string;

    /**
     * Kubernetes namespace, where model trainings will be deployed
     */
    namespace?: string;

    /**
     * Node pools to run packaging tasks on
     */
    nodePools?: Array<models.NodePool>;

    outputConnectionID?: string;

    packagerIntegrationNamespace?: string;

    /**
     * Storage backend for packaging integrations. Available options:   * kubernetes   * postgres
     */
    packagingIntegrationRepositoryType?: string;

    serviceAccount?: string;

    /**
     * Timeout for full training process
     */
    timeout?: string;

    /**
     * Kubernetes tolerations for model packaging pods
     */
    tolerations?: string;

}
