/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelTrainingConfig {
    /**
     * Default resources for training pods
     */
    defaultResources?: models.ResourceRequirements;

    /**
     * Enable deployment API/operator
     */
    enabled?: boolean;

    /**
     * Node pools to run GPU training tasks on
     */
    gpuNodePools?: Array<models.NodePool>;

    /**
     * Kubernetes tolerations for GPU model trainings pods
     */
    gpuTolerations?: string;

    metricUrl?: string;

    modelTrainerImage?: string;

    /**
     * Kubernetes namespace, where model trainings will be deployed
     */
    namespace?: string;

    /**
     * Node pools to run training tasks on
     */
    nodePools?: Array<models.NodePool>;

    outputConnectionID?: string;

    serviceAccount?: string;

    /**
     * Timeout for full training process
     */
    timeout?: string;

    /**
     * Kubernetes tolerations for model trainings pods
     */
    tolerations?: string;

    trainingIntegrationNamespace?: string;

    /**
     * Storage backend for training integrations. Available options:   * kubernetes   * postgres
     */
    trainingIntegrationRepositoryType?: string;

}
