/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelRoute {
    /**
     * CreatedAt
     */
    createdAt?: string;

    /**
     * Default routes cannot be deleted by  They are managed by system One ModelDeployment has exactly one default Route that gives 100% traffic to the model
     */
    _default?: boolean;

    /**
     * Model route id
     */
    id?: string;

    /**
     * Model route specification
     */
    spec?: models.ModelRouteSpec;

    /**
     * Model route status
     */
    status?: models.ModelRouteStatus;

    /**
     * UpdatedAt
     */
    updatedAt?: string;

}
