/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelPackagingConfig {
    /**
     * Default resources for packaging pods
     */
    defaultResources?: models.ResourceRequirements;

    /**
     * Enable packaging API/operator
     */
    enabled?: boolean;

    modelPackagerImage?: string;

    /**
     * Kubernetes namespace, where model trainings will be deployed
     */
    namespace?: string;

    /**
     * Kubernetes node selectors for model packaging pods
     */
    nodeSelector?: { [key: string]: string; };

    outputConnectionID?: string;

    packagerIntegrationNamespace?: string;

    serviceAccount?: string;

    /**
     * Timeout for full training process
     */
    timeout?: string;

    /**
     * Kubernetes tolerations for model packaging pods
     */
    toleration?: { [key: string]: string; };

}
