/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelTrainingSpec {
    /**
     * AlgorithmSource for training
     */
    algorithmSource?: models.AlgorithmSource;

    args?: Array<string>;

    /**
     * Input data for a training
     */
    data?: Array<models.DataBindingDir>;

    /**
     * Model training file. It can be python\\bash script or jupiter notebook
     */
    entrypoint?: string;

    /**
     * Custom environment variables that should be set before entrypoint invocation.
     */
    envs?: Array<models.EnvironmentVariable>;

    /**
     * Model training hyperParameters in parameter:value format
     */
    hyperParameters?: { [key: string]: string; };

    /**
     * Train image
     */
    image?: string;

    /**
     * Model Identity
     */
    model?: models.ModelIdentity;

    /**
     * Node selector for specifying a node pool
     */
    nodeSelector?: { [key: string]: string; };

    /**
     * Name of Connection to storage where training output artifact will be stored. Permitted connection types are defined by specific toolchain
     */
    outputConnection?: string;

    /**
     * Resources for model container The same format like k8s uses for pod resources.
     */
    resources?: models.ResourceRequirements;

    /**
     * IntegrationName of toolchain
     */
    toolchain?: string;

    /**
     * Directory with model scripts/files in a git repository
     */
    workDir?: string;

}
