/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RouteEvent {
    /**
     * When event is raised
     */
    datetime?: string;

    /**
     * EntityID contains ID of ModelRoute for ModelRouteDeleted and ModelRouteDeletionMarkIsSet event types Does not make sense in case of ModelRouteUpdate, ModelRouteCreate, ModelRouteStatusUpdated events
     */
    entityID?: string;

    /**
     * Payload contains ModelRoute for ModelRouteUpdate, ModelRouteCreate, ModelRouteStatusUpdated  events. Does not make sense in case of ModelRouteDelete, ModelRouteDeletionMarkIsSet events
     */
    payload?: models.ModelRoute;

    /**
     * Possible values: ModelRouteCreate, ModelRouteUpdate, ModelRouteDeleted, ModelRouteDeletionMarkIsSet, ModelRouteStatusUpdated
     */
    type?: string;

}
