/**
 * API Gateway
 * This is an API Gateway webServer.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TrainingIntegration {
    /**
     * CreatedAt
     */
    createdAt?: string;

    /**
     * Training integration id
     */
    id?: string;

    /**
     * Training integration specification
     */
    spec?: models.TrainingIntegrationSpec;

    /**
     * Training integration status
     */
    status?: models.TrainingIntegrationStatus;

    /**
     * UpdatedAt
     */
    updatedAt?: string;

}
